name: Daily Analysis

on:
  schedule:
    - cron: '30 9 * * 1-5'   # 09:30 UTC = 北京时间 17:30（工作日）
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        run: python run_daily.py --top 100 --out ./reports

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/*
