name: Daily Analysis

on:
  schedule:
    - cron: '30 9 * * 1-5'   # 工作日 09:30 UTC
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: daily-analysis-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 4G 交换区，缓解 OOM
      - name: Add 4G swap (prevent OOM)
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache AkShare data
        uses: actions/cache@v4
        with:
          path: |
            ~/.akshare
            ~/.cache/akshare
            ~/.local/share/akshare
          key: akshare-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            akshare-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare report dir
        run: mkdir -p reports

      # —— Lite-Safe 参数：先稳定产出，再逐步加大 ——
      - name: Run daily analysis (lite-safe)
        env:
          RUN_ARGS: >-
            --top 350
            --ind-top-k 6
            --per-industry-top 3
            --ml-lookback-days 720
            --ml-min-rows 50
            --eval-days 40
            --w-ml 0.35
            --max-train-samples 60000
        run: |
          set -e
          python -m py_compile run_daily.py
          python -u run_daily.py $RUN_ARGS 2>&1 | tee reports/runtime.log

      - name: Upload report artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/*
          if-no-files-found: warn
          retention-days: 14
