name: Daily Analysis (signal + discovery)

on:
  schedule:
    # 每个工作日 09:30 UTC 触发（= 北京时间 17:30）
    - cron: '30 9 * * 1-5'
  # 允许在 Actions 页面手动触发
  workflow_dispatch:

permissions:
  contents: read

# 同一分支只运行一个实例
concurrency:
  group: daily-analysis-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analyze:
    name: Daily Analysis - ${{ matrix.id }}
    runs-on: ubuntu-latest
    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        include:
          # A. 信号版（更精准，用于实际下单）
          - id: signal
            run_args: >-
              --top 600
              --ind-top-k 10
              --per-industry-top 4
              --ml-lookback-days 1200
              --ml-min-rows 40
              --entry-only
          # B. 发现版（覆盖更广，用于浏览与研究）
          - id: discovery
            run_args: >-
              --top 700
              --ind-top-k 12
              --per-industry-top 5
              --ml-lookback-days 1200
              --ml-min-rows 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.id }} analysis
        env:
          RUN_ARGS: ${{ matrix.run_args }}
          MATRIX_ID: ${{ matrix.id }}
        run: |
          set -e
          # 语法检查（可选）
          python -m py_compile run_daily.py

          # 清理并运行
          rm -rf reports || true
          python run_daily.py $RUN_ARGS

          # 将本轮产出移到独立目录，避免两套报告互相覆盖
          OUTDIR="reports_${MATRIX_ID}"
          mkdir -p "$OUTDIR"
          if compgen -G "reports/*" > /dev/null; then
            mv reports/* "$OUTDIR"/
          else
            echo "No files generated for ${MATRIX_ID} at $(date -u '+%F %T') UTC" > "$OUTDIR/README.txt"
          fi

      - name: Upload ${{ matrix.id }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report-${{ matrix.id }}
          path: reports_${{ matrix.id }}/*
          if-no-files-found: warn
          retention-days: 7
