name: Daily Analysis

on:
  schedule:
    # 每个工作日 09:30 UTC 触发（= 北京时间 17:30）
    - cron: '30 9 * * 1-5'
  # 允许在 Actions 页面手动触发
  workflow_dispatch:

permissions:
  contents: read

# 同一分支保证只运行一个实例
concurrency:
  group: daily-analysis-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'   # 缓存 pip 依赖，加速执行

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          # 关键：确保 scikit-learn 存在（即使 requirements.txt 漏写也能装上）
          pip install "scikit-learn>=1.4,<1.6"

      - name: Run daily analysis
        # 在这里改运行参数最方便
        env:
          RUN_ARGS: >-
            --top 500
            --ind-top-k 8
            --per-industry-top 3
            --ml-lookback-days 1200
            --ml-min-rows 50
            --entry-only
        run: |
          set -e
          python -m py_compile run_daily.py
          python run_daily.py $RUN_ARGS

      # 兜底：如果没有生成任何报告，自动写一份“无候选”的占位报告，保证有 Artifact 可下载
      - name: Ensure reports (fallback when empty)
        run: |
          mkdir -p reports
          if [ -z "$(ls -A reports 2>/dev/null)" ]; then
            D=$(date +%F)
            echo "<html><head><meta charset='utf-8'><title>Daily Report ${D}</title></head><body><h1>无候选股票</h1><p>今日没有满足入场条件的个股。</p><p>参数：${RUN_ARGS}</p></body></html>" > reports/report_${D}.html
            printf "message\n无候选股票（参数：%s）\n" "${RUN_ARGS}" > reports/report_${D}.csv
          fi

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/*
          if-no-files-found: warn
          retention-days: 7
