name: Daily Analysis

on:
  schedule:
    # 每个工作日 09:30 UTC 触发（= 北京时间 17:30）
    - cron: '30 9 * * 1-5'
  # 允许在 Actions 页面手动触发
  workflow_dispatch:

permissions:
  contents: read

# 同一分支只跑一个实例
concurrency:
  group: daily-analysis-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        run: |
          set -e
          # 语法检查（可选）
          python -m py_compile run_daily.py
          # —— 真正运行参数（可按需调整）——
          python run_daily.py \
            --top 600 \
            --ind-top-k 10 \
            --per-industry-top 4 \
            --ml-lookback-days 1200 \
            --ml-min-rows 50 \
            --eval-days 60 \
            --w-ml 0.40
          # 只看“入场信号=1”的票时，改用下面这一行（把上面那行注释掉）：
          # python run_daily.py --top 600 --ind-top-k 10 --per-industry-top 4 --ml-lookback-days 1200 --ml-min-rows 50 --eval-days 60 --w-ml 0.40 --entry-only

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/*
          if-no-files-found: warn
          retention-days: 14
