name: Daily Analysis

on:
  schedule:
    # 每个工作日 09:30 UTC 触发（= 北京时间 17:30）
    - cron: '30 9 * * 1-5'
  # 允许在 Actions 页面手动触发
  workflow_dispatch:

permissions:
  contents: read

# 同一分支只跑一个实例
concurrency:
  group: daily-analysis-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily analysis
        env:
          RUN_ARGS: >-
            --top 600
            --ind-top-k 10
            --per-industry-top 4
            --ml-lookback-days 1200
            --ml-min-rows 50
            --eval-days 60
            # 调高模型权重一点（可按需调整）
            --w-ml 0.40
            # 稳定期先不要硬过滤，观察一段时间后再加：
            # --entry-only
        run: |
          set -e
          python -m py_compile run_daily.py
          python run_daily.py $RUN_ARGS

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: reports/*
          if-no-files-found: warn
          retention-days: 14
